### ISSUE TITLE
Outdated for current versions of Rails

### ISSUE THREAD

**Issue by andreas1974** [kranzky/megahal-server#2]
Problems arose trying to install megahal-server on current version of Rails (ver 7.0.2). Can you update the code to make it accept Rails 7.0.2?

**Comment by kranzky** [comment]
This project is very old and I don't have much time to look at it right now sorry.

**Comment by andreas1974** [comment]
Please take your time, it would be great to chat with MegaHal some day in the the future. We are a bunch of friends waiting patiently for the return of MegaHal.

**Comment by kranzky** [comment]
Good to know! You can run it directly from the console with the megahal gem: https://github.com/kranzky/megahal

**Comment by kranzky** [comment]
I am starting to look at this today :)

**Comment by Fredrichl** [comment]
Nice, looking forward to this!

**Comment by kranzky** [comment]
Basic echo server deploying to fly.io and being served at https://megahal.kranzky.com/

This is just a WIP; still need to daemonize MegaHAL and get that hooked up.

**Comment by kranzky** [comment]
First version is now deployed and running here: https://megahal.kranzky.com/

If you check out the repo locally, and provided you have redis running and dependencies installed, then all you should need to do is run the `dev` script and point your browser to http://127.0.0.1:3000/

**Comment by andreas1974** [comment]
This is great news, thank you so much! Will try to set up a MegaHal server later on.
Are the steps in the [Readme/Deployment](https://github.com/kranzky/megahal-server#readme) section all that's needed?

**Comment by kranzky** [comment]
It depends @andreas1974. If you are used to developing Rails apps yourself, then running the `dev` script should be all you need to do to get it running locally. The `fly.toml` files should be enough to deploy to fly.io if you want to do that, but you will need to do some additional configuration, such as creating a volume and defining various secrets. Let me know and I can write a quick guide. Not sure about deploying to other services such as Heroku or AWS.

**Comment by andreas1974** [comment]
We (some friends and I) plan to set up a server, so that we can have a MegaHal of our own, just like the one you put at https://megahal.kranzky.com/ . Would you happen to know whether Raspberry PI would suffice for running Rails and the MegaHal server software?
It would be very helpful with a quick guide, since we are not experienced Rails developers. Such a guide would be splendid!

**Comment by kranzky** [comment]
Getting it up-and-running under Linux on your Raspberry Pi should be straightforward:

- Install Redis. MegaHAL assumes it'll be running at the URL `redis://localhost:6379/1`. If this isn't the case, then define the `REDIS_URL` environment variable to point at your local Redis installation.
- Install RVM (the Ruby Version Manager).
- Checkout this repository. When you enter the `megahal-server` directory, RVM should fire up and install Ruby v3.1.0 for you automatically. If that doesn't happen, run `rvm use 3.1.0`.
- Run `./bin/setup` to install dependencies.
- Run `./bin/dev` to start the server.

Good luck!
